### ISSUE TITLE
Repeated Login Requests

### ISSUE THREAD

**Issue by Abus00** [ls1intum/artemis-ios#189]
# Issue: Repeated Login Requests

**Description:**
I am required to log into the app using my TUM credentials multiple times throughout the day. I have checked whether this issue is related to app updates, but it appears not to be.

**Possible Causes:**
Expiring tokens, session timeout, cache issue?

**Device Information:**
- Device: iPhone 13
- iOS Version: 17.6.1
- App Version: 1.3.2

**Comment by Abus00** [comment]
I found a workaround: if you're prompted to log in again, you can just close the app and reopen it. You'll be automatically logged in. Maybe this helps with resolving the issue.

**Comment by simonbohnen** [comment]
I really would like to solve this issue. It must have something to do with the `isLoggedIn` attribute of the `RootViewModel`, right?

**Comment by anian03** [comment]
Yes, both of your observations appear to be correct based on what I've been able to discover as well. Quite a few login prompts don't actually require you to log in again and a restart of the app is enough.
It very likely has something to do with some requests being made or something being done in the background state, which seems to lead to a state where isLoggedIn in RootViewModel is set to false. Unfortunately I haven't been able to figure out how exactly this occurs though.

I was considering re-writing the login code to a different, more unified approach (instead of having it spread across multiple classes), but this is a fairly complex task.
So for the mean time a workaround would be great, possibly something like trying a web request when the login screen appears and manually setting isLoggedIn to true if it succeeds. The problem is that I haven't been able to reproduce the issue to test such a workaround.

**Comment by simonbohnen** [comment]
For me the bug hasn't occurred anymore over the past days although nothing changed. Seems very spurious 😕
