### ISSUE TITLE
`Communication:` Text formatting options on text-field have inconsistent formatting

### ISSUE THREAD

**Issue by ahbitaqu** [ls1intum/artemis-ios#216]
When writing a message on the iOS App, the options to make your text Bold, Italic and Underlined are too close to each other. If compared with the other options like quotes and links this looks very odd.

![IMG_0544 2024-11-14 19_05_31](https://github.com/user-attachments/assets/383c9cf9-f2a7-42d3-b227-597203dd6c90)

My proposal would be to make the spacing between all the formatting options consistent (If these 3 should be different than the other options because of their more frequent use, then I'd suggest for example changing the background color of the options).

**Comment by anian03** [comment]
Hey, could you elaborate on what exactly is inconsistent here? This is just a single button, not three separate ones. Would you suggest using a different icon for it? I've just used the current one because in my opinion it was the most descriptive option.

<img src="https://github.com/user-attachments/assets/3bd26ddb-1f32-4e27-8d02-d04eea9f4b26" alt="Format menu" width="300">
